In [1]:
import pandas as pd 
import numpy as np
from datetime import datetime as dt
from pathlib import Path
%matplotlib inline 
import seaborn as sns

In [8]:
csv_path_spy= Path("../Project_1/five_min_spy_data_frame.csv")
csv_path_spy

WindowsPath('../Project_1/five_min_spy_data_frame.csv')

In [9]:
spy_df = pd.read_csv(csv_path_spy, index_col="date",infer_datetime_format= True,
                    parse_dates = True)

spy_df.head()

                        high     low      open     close   volume
date
2019-09-18 16:00:00  301.120  300.88  300.9200  301.1000  2610142
2019-09-18 15:55:00  301.115  300.78  301.0700  300.9300  1530074
2019-09-18 15:50:00  301.220  300.87  301.1100  301.0750  1008201
2019-09-18 15:45:00  301.110  300.79  300.8371  301.1099  1331334
2019-09-18 15:40:00  300.860  300.68  300.8600  300.8300  1685182

In [10]:
spy_df.reset_index(inplace=True)

spy_df.head()

                 date     high     low      open     close   volume
0 2019-09-18 16:00:00  301.120  300.88  300.9200  301.1000  2610142
1 2019-09-18 15:55:00  301.115  300.78  301.0700  300.9300  1530074
2 2019-09-18 15:50:00  301.220  300.87  301.1100  301.0750  1008201
3 2019-09-18 15:45:00  301.110  300.79  300.8371  301.1099  1331334
4 2019-09-18 15:40:00  300.860  300.68  300.8600  300.8300  1685182

In [11]:
spy_df.set_index('date',inplace=True)
spy_df.sort_index(ascending=False,inplace=True)

spy_df.reset_index(inplace=True)
spy_df.head()

                 date     high     low      open     close   volume
0 2019-09-18 16:00:00  301.120  300.88  300.9200  301.1000  2610142
1 2019-09-18 15:55:00  301.115  300.78  301.0700  300.9300  1530074
2 2019-09-18 15:50:00  301.220  300.87  301.1100  301.0750  1008201
3 2019-09-18 15:45:00  301.110  300.79  300.8371  301.1099  1331334
4 2019-09-18 15:40:00  300.860  300.68  300.8600  300.8300  1685182

In [12]:
# spy_df.set_index('date',inplace=True)
spy_df['time']=spy_df['date'].dt.time

In [13]:
# spy_df.set_index('date',inplace=True)

# spy_df['date_dt'] = 
# spy_df['date'] = pd.to_datetime(spy_df['date'])

# spy_df['time']=spy_df['date'].dt.time


spy_df.head()
# spy_df['date'].datetime.today().strftime('%A')

                 date     high     low      open     close   volume      time
0 2019-09-18 16:00:00  301.120  300.88  300.9200  301.1000  2610142  16:00:00
1 2019-09-18 15:55:00  301.115  300.78  301.0700  300.9300  1530074  15:55:00
2 2019-09-18 15:50:00  301.220  300.87  301.1100  301.0750  1008201  15:50:00
3 2019-09-18 15:45:00  301.110  300.79  300.8371  301.1099  1331334  15:45:00
4 2019-09-18 15:40:00  300.860  300.68  300.8600  300.8300  1685182  15:40:00

In [14]:
spy_df.set_index('date',inplace=True)

spy_df.sort_index(inplace=True)

In [15]:
# from datetime import datetime
# spy_df['date'].datetime.today().strftime('%A')

In [16]:
spy_df.head()

                         high       low      open     close   volume      time
date
2019-08-28 09:35:00  286.4500  285.5100  286.1400  285.5800  3314079  09:35:00
2019-08-28 09:40:00  286.2480  285.5173  285.5907  285.7807  2108159  09:40:00
2019-08-28 09:45:00  286.3500  285.5300  285.7700  286.2500  1180551  09:45:00
2019-08-28 09:50:00  286.7962  286.2357  286.2803  286.4403  1594274  09:50:00
2019-08-28 09:55:00  286.9000  286.3800  286.5900  286.7910  1040474  09:55:00

In [17]:
spy_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1115 entries, 2019-08-28 09:35:00 to 2019-09-18 16:00:00
Data columns (total 6 columns):
high      1115 non-null float64
low       1115 non-null float64
open      1115 non-null float64
close     1115 non-null float64
volume    1115 non-null int64
time      1115 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 61.0+ KB

In [18]:
spy_df= spy_df.iloc[179:]

In [19]:
spy_df.head()

                         high       low      open     close   volume      time
date
2019-09-03 09:35:00  291.0718  290.5613  290.5776  290.6175  4822146  09:35:00
2019-09-03 09:40:00  291.0900  290.6000  290.6100  290.9500  1320719  09:40:00
2019-09-03 09:45:00  291.3791  290.9088  290.9557  291.0957   738767  09:45:00
2019-09-03 09:50:00  291.3050  290.6600  291.1000  290.8850   791261  09:50:00
2019-09-03 09:55:00  291.5400  290.9000  290.9000  291.4900   996429  09:55:00

## NYSE Market hours are 9:30 AM to 4 PM

In [20]:
spy_df.iloc[0:13:]

                         high       low      open     close   volume      time
date
2019-09-03 09:35:00  291.0718  290.5613  290.5776  290.6175  4822146  09:35:00
2019-09-03 09:40:00  291.0900  290.6000  290.6100  290.9500  1320719  09:40:00
2019-09-03 09:45:00  291.3791  290.9088  290.9557  291.0957   738767  09:45:00
2019-09-03 09:50:00  291.3050  290.6600  291.1000  290.8850   791261  09:50:00
2019-09-03 09:55:00  291.5400  290.9000  290.9000  291.4900   996429  09:55:00
2019-09-03 10:00:00  291.6000  291.2500  291.4800  291.3500   469532  10:00:00
2019-09-03 10:05:00  291.6200  289.7200  291.1700  289.7500  5496366  10:05:00
2019-09-03 10:10:00  290.1120  289.5715  289.7394  289.6644  1865194  10:10:00
2019-09-03 10:15:00  289.9450  289.3800  289.6500  289.4400  1364689  10:15:00
2019-09-03 10:20:00  289.9500  289.2700  289.4600  289.8300  1196459  10:20:00
2019-09-03 10:25:00  290.0200  289.7400  289.8200  289.8200  1079803  10:25:00
2019-09-03 10:30:00  290.5581  289.7173  289.8316  290.2616   843739  10:30:00
2019-09-03 10:35:00  290.2500  289.7400  290.2500  289.9900   858742  10:35:00

In [21]:
spy_df=spy_df[['time','open','close','volume']]
spy_df.head()

                         time      open     close   volume
date
2019-09-03 09:35:00  09:35:00  290.5776  290.6175  4822146
2019-09-03 09:40:00  09:40:00  290.6100  290.9500  1320719
2019-09-03 09:45:00  09:45:00  290.9557  291.0957   738767
2019-09-03 09:50:00  09:50:00  291.1000  290.8850   791261
2019-09-03 09:55:00  09:55:00  290.9000  291.4900   996429

In [22]:
spy_df['Returns'] = ((spy_df['close'] - spy_df['open'])/ spy_df['open'])
spy_df.head()

                         time      open     close   volume   Returns
date
2019-09-03 09:35:00  09:35:00  290.5776  290.6175  4822146  0.000137
2019-09-03 09:40:00  09:40:00  290.6100  290.9500  1320719  0.001170
2019-09-03 09:45:00  09:45:00  290.9557  291.0957   738767  0.000481
2019-09-03 09:50:00  09:50:00  291.1000  290.8850   791261 -0.000739
2019-09-03 09:55:00  09:55:00  290.9000  291.4900   996429  0.002028

In [23]:
# spy_df.head()
returns_df = spy_df[['time','Returns','volume']]
returns_df

                         time   Returns   volume
date
2019-09-03 09:35:00  09:35:00  0.000137  4822146
2019-09-03 09:40:00  09:40:00  0.001170  1320719
2019-09-03 09:45:00  09:45:00  0.000481   738767
2019-09-03 09:50:00  09:50:00 -0.000739   791261
2019-09-03 09:55:00  09:55:00  0.002028   996429
2019-09-03 10:00:00  10:00:00 -0.000446   469532
2019-09-03 10:05:00  10:05:00 -0.004877  5496366
2019-09-03 10:10:00  10:10:00 -0.000259  1865194
2019-09-03 10:15:00  10:15:00 -0.000725  1364689
2019-09-03 10:20:00  10:20:00  0.001278  1196459
2019-09-03 10:25:00  10:25:00  0.000000  1079803
2019-09-03 10:30:00  10:30:00  0.001484   843739
2019-09-03 10:35:00  10:35:00 -0.000896   858742
2019-09-03 10:40:00  10:40:00  0.000362   690629
2019-09-03 10:45:00  10:45:00  0.001241  1342137
2019-09-03 10:50:00  10:50:00  0.000207   729874
2019-09-03 10:55:00  10:55:00  0.000757   629405
2019-09-03 11:00:00  11:00:00  0.000413   815404
2019-09-03 11:05:00  11:05:00 -0.001135   755109
2019-09-03 11:10:00  11:10:00  0.000000   671076
2019-09-03 11:15:00  11:15:00 -0.002099   829850
2019-09-03 11:20:00  11:20:00  0.001052   598221
2019-09-03 11:25:00  11:25:00  0.000724   533074
2019-09-03 11:30:00  11:30:00  0.000276  1462735
2019-09-03 11:35:00  11:35:00  0.000310   622800
2019-09-03 11:40:00  11:40:00  0.000516   640993
2019-09-03 11:45:00  11:45:00 -0.000069   260992
2019-09-03 11:50:00  11:50:00  0.001342   611509
2019-09-03 11:55:00  11:55:00 -0.000402   295219
2019-09-03 12:00:00  12:00:00 -0.000825   256612
...                       ...       ...      ...
2019-09-18 13:35:00  13:35:00  0.000267   405050
2019-09-18 13:40:00  13:40:00  0.000534   804637
2019-09-18 13:45:00  13:45:00  0.000206   777321
2019-09-18 13:50:00  13:50:00 -0.000017   241690
2019-09-18 13:55:00  13:55:00  0.000616   676436
2019-09-18 14:00:00  14:00:00  0.000167   524310
2019-09-18 14:05:00  14:05:00 -0.001731  4079514
2019-09-18 14:10:00  14:10:00 -0.000867  1786468
2019-09-18 14:15:00  14:15:00 -0.002969  2001689
2019-09-18 14:20:00  14:20:00  0.000184  2086006
2019-09-18 14:25:00  14:25:00  0.000888  1128360
2019-09-18 14:30:00  14:30:00 -0.000184   722093
2019-09-18 14:35:00  14:35:00  0.001373  1622858
2019-09-18 14:40:00  14:40:00 -0.000335  2057417
2019-09-18 14:45:00  14:45:00  0.001038  2720779
2019-09-18 14:50:00  14:50:00 -0.001204  4129627
2019-09-18 14:55:00  14:55:00  0.001238  1801964
2019-09-18 15:00:00  15:00:00 -0.000334  1335248
2019-09-18 15:05:00  15:05:00 -0.000100  1907093
2019-09-18 15:10:00  15:10:00  0.001170  1270452
2019-09-18 15:15:00  15:15:00  0.000083  3096953
2019-09-18 15:20:00  15:20:00  0.000968   894520
2019-09-18 15:25:00  15:25:00  0.000094  2472039
2019-09-18 15:30:00  15:30:00  0.000434   927824
2019-09-18 15:35:00  15:35:00  0.002433  2018739
2019-09-18 15:40:00  15:40:00 -0.000100  1685182
2019-09-18 15:45:00  15:45:00  0.000907  1331334
2019-09-18 15:50:00  15:50:00 -0.000116  1008201
2019-09-18 15:55:00  15:55:00 -0.000465  1530074
2019-09-18 16:00:00  16:00:00  0.000598  2610142

[936 rows x 3 columns]

In [24]:
# returns_df.iloc[:13:] ### 935-1035
# returns_df.iloc[13:26:] 1040-1140
# returns_df.iloc[26:39:] 1145-12-45
# returns_df.iloc[39:52:] 1250-150
# returns_df.iloc[52:65:] 155-255
# returns_df.iloc[65:78:] 3-4
#next day morning # returns_df.iloc[78:91:]

In [25]:
returns_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 936 entries, 2019-09-03 09:35:00 to 2019-09-18 16:00:00
Data columns (total 3 columns):
time       936 non-null object
Returns    936 non-null float64
volume     936 non-null int64
dtypes: float64(1), int64(1), object(1)
memory usage: 29.2+ KB

In [26]:
bin1 = 0
bin2 = 78
list_of_df = []
while bin2 < 937:
    dataframe = spy_df.iloc[bin1:bin2]
    bin1 += 78
    bin2 += 78
    list_of_df.append(dataframe)
print(list_of_df)

[                         time      open     close   volume   Returns
date
2019-09-03 09:35:00  09:35:00  290.5776  290.6175  4822146  0.000137
2019-09-03 09:40:00  09:40:00  290.6100  290.9500  1320719  0.001170
2019-09-03 09:45:00  09:45:00  290.9557  291.0957   738767  0.000481
2019-09-03 09:50:00  09:50:00  291.1000  290.8850   791261 -0.000739
2019-09-03 09:55:00  09:55:00  290.9000  291.4900   996429  0.002028
2019-09-03 10:00:00  10:00:00  291.4800  291.3500   469532 -0.000446
2019-09-03 10:05:00  10:05:00  291.1700  289.7500  5496366 -0.004877
2019-09-03 10:10:00  10:10:00  289.7394  289.6644  1865194 -0.000259
2019-09-03 10:15:00  10:15:00  289.6500  289.4400  1364689 -0.000725
2019-09-03 10:20:00  10:20:00  289.4600  289.8300  1196459  0.001278
2019-09-03 10:25:00  10:25:00  289.8200  289.8200  1079803  0.000000
2019-09-03 10:30:00  10:30:00  289.8316  290.2616   843739  0.001484
2019-09-03 10:35:00  10:35:00  290.2500  289.9900   858742 -0.000896
2019-09-03 10:40:00  10:40:00  289.9850  290.0900   690629  0.000362
2019-09-03 10:45:00  10:45:00  290.0800  290.4400  1342137  0.001241
2019-09-03 10:50:00  10:50:00  290.4500  290.5100   729874  0.000207
2019-09-03 10:55:00  10:55:00  290.5000  290.7200   629405  0.000757
2019-09-03 11:00:00  11:00:00  290.7300  290.8500   815404  0.000413
2019-09-03 11:05:00  11:05:00  290.8200  290.4900   755109 -0.001135
2019-09-03 11:10:00  11:10:00  290.4900  290.4900   671076  0.000000
2019-09-03 11:15:00  11:15:00  290.5000  289.8901   829850 -0.002099
2019-09-03 11:20:00  11:20:00  289.8450  290.1500   598221  0.001052
2019-09-03 11:25:00  11:25:00  290.1300  290.3400   533074  0.000724
2019-09-03 11:30:00  11:30:00  290.3500  290.4300  1462735  0.000276
2019-09-03 11:35:00  11:35:00  290.4200  290.5100   622800  0.000310
2019-09-03 11:40:00  11:40:00  290.5000  290.6500   640993  0.000516
2019-09-03 11:45:00  11:45:00  290.6300  290.6100   260992 -0.000069
2019-09-03 11:50:00  11:50:00  290.6100  291.0000   611509  0.001342
2019-09-03 11:55:00  11:55:00  290.9970  290.8800   295219 -0.000402
2019-09-03 12:00:00  12:00:00  290.8700  290.6300   256612 -0.000825
...                       ...       ...       ...      ...       ...
2019-09-03 13:35:00  13:35:00  290.2000  289.9550   565814 -0.000844
2019-09-03 13:40:00  13:40:00  289.9500  289.9800   583137  0.000103
2019-09-03 13:45:00  13:45:00  289.9850  289.8700   432740 -0.000397
2019-09-03 13:50:00  13:50:00  289.8800  289.9200   863105  0.000138
2019-09-03 13:55:00  13:55:00  289.9100  289.6800   467943 -0.000793
2019-09-03 14:00:00  14:00:00  289.6900  289.7800   209199  0.000311
2019-09-03 14:05:00  14:05:00  289.7700  289.9700   357103  0.000690
2019-09-03 14:10:00  14:10:00  289.9765  289.9550   187631 -0.000074
2019-09-03 14:15:00  14:15:00  289.9550  290.0200   320083  0.000224
2019-09-03 14:20:00  14:20:00  290.0100  289.8600   327984 -0.000517
2019-09-03 14:25:00  14:25:00  289.8500  289.7800   321744 -0.000242
2019-09-03 14:30:00  14:30:00  289.7752  290.0000   178488  0.000776
2019-09-03 14:35:00  14:35:00  290.0000  289.9100   425579 -0.000310
2019-09-03 14:40:00  14:40:00  289.9300  290.0400   387009  0.000379
2019-09-03 14:45:00  14:45:00  290.0450  290.1000   305891  0.000190
2019-09-03 14:50:00  14:50:00  290.1000  290.1000   388879  0.000000
2019-09-03 14:55:00  14:55:00  290.1100  290.1895   691893  0.000274
2019-09-03 15:00:00  15:00:00  290.1800  290.1900   303748  0.000034
2019-09-03 15:05:00  15:05:00  290.1934  290.0350   622163 -0.000546
2019-09-03 15:10:00  15:10:00  290.0200  290.1800   866722  0.000552
2019-09-03 15:15:00  15:15:00  290.1800  290.1701   422380 -0.000034
2019-09-03 15:20:00  15:20:00  290.1800  290.3950   525500  0.000741
2019-09-03 15:25:00  15:25:00  290.4100  290.5100   519614  0.000344
2019-09-03 15:30:00  15:30:00  290.5200  290.4750   560434 -0.000155
2019-09-03 15:35:00  15:35:00  290.4800  290.5900   648505  0.000379
2019-09-03 15:40:00  15:40:00  290.5939  290.6517   585010  0.000199
2019-09-03 15:45:00  15:45:00  290.6600  290.5800   653671 -0.000275
2019-09-03 15:50:00  15:50:00  290.5900  290.7100   848093  0.000413
2019-09-03 15:55:00  15:55:00  290.7000  290.9600  1756085  0.000894
2019-09-03 16:00:00  16:00:00  290.9500  290.7700  2411640 -0.000619

[78 rows x 5 columns],                          time      open     close   volume       Returns
date
2019-09-04 09:35:00  09:35:00  293.1400  293.1100  3465261 -1.023402e-04
2019-09-04 09:40:00  09:40:00  293.1300  293.0000   870593 -4.434892e-04
2019-09-04 09:45:00  09:45:00  293.0100  293.0400  1170676  1.023856e-04
2019-09-04 09:50:00  09:50:00  293.0400  292.9400  1185281 -3.412503e-04
2019-09-04 09:55:00  09:55:00  292.9350  292.9700   895567  1.194804e-04
2019-09-04 10:00:00  10:00:00  292.9800  292.9500   533763 -1.023961e-04
2019-09-04 10:05:00  10:05:00  292.9415  292.9400   730016 -5.120476e-06
2019-09-04 10:10:00  10:10:00  292.9400  292.7301   768274 -7.165290e-04
2019-09-04 10:15:00  10:15:00  292.7300  292.3935   749442 -1.149523e-03
2019-09-04 10:20:00  10:20:00  292.3900  292.6400   422938  8.550224e-04
2019-09-04 10:25:00  10:25:00  292.6298  292.5200   556046 -3.752181e-04
2019-09-04 10:30:00  10:30:00  292.5300  292.7000   434299  5.811370e-04
2019-09-04 10:35:00  10:35:00  292.7000  292.7800   449591  2.733174e-04
2019-09-04 10:40:00  10:40:00  292.7600  292.6400   259941 -4.098921e-04
2019-09-04 10:45:00  10:45:00  292.6400  292.5600   196609 -2.733734e-04
2019-09-04 10:50:00  10:50:00  292.5700  292.6750   297005  3.588885e-04
2019-09-04 10:55:00  10:55:00  292.6800  292.7900   371188  3.758371e-04
2019-09-04 11:00:00  11:00:00  292.7900  292.8500   380582  2.049250e-04
2019-09-04 11:05:00  11:05:00  292.8600  292.8418   334331 -6.214574e-05
2019-09-04 11:10:00  11:10:00  292.8500  292.8600   799995  3.414717e-05
2019-09-04 11:15:00  11:15:00  292.8799  292.7100   332295 -5.801013e-04
2019-09-04 11:20:00  11:20:00  292.7100  292.9200   291470  7.174336e-04
2019-09-04 11:25:00  11:25:00  292.9200  292.9900   273833  2.389731e-04
2019-09-04 11:30:00  11:30:00  292.9900  293.2100   551423  7.508789e-04
2019-09-04 11:35:00  11:35:00  293.2200  293.3300   520148  3.751449e-04
2019-09-04 11:40:00  11:40:00  293.3300  293.3150   431676 -5.113694e-05
2019-09-04 11:45:00  11:45:00  293.3200  293.4750   594219  5.284331e-04
2019-09-04 11:50:00  11:50:00  293.4800  293.4450   438085 -1.192586e-04
2019-09-04 11:55:00  11:55:00  293.4500  293.4400   248540 -3.407736e-05
2019-09-04 12:00:00  12:00:00  293.4400  293.4500   223996  3.407852e-05
...                       ...       ...       ...      ...           ...
2019-09-04 13:35:00  13:35:00  293.5400  293.5100   282726 -1.022007e-04
2019-09-04 13:40:00  13:40:00  293.5083  293.3400   273029 -5.734080e-04
2019-09-04 13:45:00  13:45:00  293.3400  293.3000   361866 -1.363605e-04
2019-09-04 13:50:00  13:50:00  293.3000  293.2429   341705 -1.946812e-04
2019-09-04 13:55:00  13:55:00  293.2400  293.1500   150783 -3.069158e-04
2019-09-04 14:00:00  14:00:00  293.1400  293.1950   232949  1.876237e-04
2019-09-04 14:05:00  14:05:00  293.2000  293.3152   273049  3.929059e-04
2019-09-04 14:10:00  14:10:00  293.3300  293.2300   199186 -3.409130e-04
2019-09-04 14:15:00  14:15:00  293.2300  293.1250   326966 -3.580807e-04
2019-09-04 14:20:00  14:20:00  293.1300  293.2300   256143  3.411456e-04
2019-09-04 14:25:00  14:25:00  293.2200  293.2800   297873  2.046245e-04
2019-09-04 14:30:00  14:30:00  293.2800  293.4000   225089  4.091653e-04
2019-09-04 14:35:00  14:35:00  293.3900  293.4800   344236  3.067589e-04
2019-09-04 14:40:00  14:40:00  293.4848  293.4850   198049  6.814663e-07
2019-09-04 14:45:00  14:45:00  293.5000  293.5510   249497  1.737649e-04
2019-09-04 14:50:00  14:50:00  293.5600  293.6100   470525  1.703229e-04
2019-09-04 14:55:00  14:55:00  293.6200  293.6200   193337  0.000000e+00
2019-09-04 15:00:00  15:00:00  293.6200  293.5600   310429 -2.043458e-04
2019-09-04 15:05:00  15:05:00  293.5600  293.6950   276879  4.598719e-04
2019-09-04 15:10:00  15:10:00  293.6900  293.6900   806111  0.000000e+00
2019-09-04 15:15:00  15:15:00  293.6900  293.8500   544560  5.447921e-04
2019-09-04 15:20:00  15:20:00  293.8550  293.6500   493268 -6.976230e-04
2019-09-04 15:25:00  15:25:00  293.6500  293.6900   313650  1.362166e-04
2019-09-04 15:30:00  15:30:00  293.6850  293.7500   265013  2.213256e-04
2019-09-04 15:35:00  15:35:00  293.7500  293.9200   773460  5.787234e-04
2019-09-04 15:40:00  15:40:00  293.9200  293.9100  1244682 -3.402286e-05
2019-09-04 15:45:00  15:45:00  293.9200  293.8901   867965 -1.017284e-04
2019-09-04 15:50:00  15:50:00  293.8900  293.9600   901406  2.381844e-04
2019-09-04 15:55:00  15:55:00  293.9500  294.0000  1973608  1.700970e-04
2019-09-04 16:00:00  16:00:00  293.9700  293.9600  3171277 -3.401708e-05

[78 rows x 5 columns],                          time      open     close   volume   Returns
date
2019-09-05 09:35:00  09:35:00  296.7900  296.8300  3255508  0.000135
2019-09-05 09:40:00  09:40:00  296.8400  297.0450  1078345  0.000691
2019-09-05 09:45:00  09:45:00  297.0500  297.0600   816997  0.000034
2019-09-05 09:50:00  09:50:00  297.0600  297.3900  1574975  0.001111
2019-09-05 09:55:00  09:55:00  297.4900  297.5800  1027245  0.000303
2019-09-05 10:00:00  10:00:00  297.5900  297.5200  1024548 -0.000235
2019-09-05 10:05:00  10:05:00  297.8158  297.9258  2031117  0.000369
2019-09-05 10:10:00  10:10:00  297.9300  298.0650  1810582  0.000453
2019-09-05 10:15:00  10:15:00  298.0800  298.2899  1177342  0.000704
2019-09-05 10:20:00  10:20:00  298.2900  298.8000  1735611  0.001710
2019-09-05 10:25:00  10:25:00  298.8000  298.3650  1626107 -0.001456
2019-09-05 10:30:00  10:30:00  298.3600  298.2100  1775354 -0.000503
2019-09-05 10:35:00  10:35:00  298.2000  298.3450   845069  0.000486
2019-09-05 10:40:00  10:40:00  298.3441  298.2850  1185047 -0.000198
2019-09-05 10:45:00  10:45:00  298.2850  298.3200  2031263  0.000117
2019-09-05 10:50:00  10:50:00  298.3200  298.0500  1259137 -0.000905
2019-09-05 10:55:00  10:55:00  298.0600  298.1400  2656301  0.000268
2019-09-05 11:00:00  11:00:00  298.1500  298.0500  1028830 -0.000335
2019-09-05 11:05:00  11:05:00  298.0400  298.1400  1593359  0.000336
2019-09-05 11:10:00  11:10:00  298.2400  298.1000  1107366 -0.000469
2019-09-05 11:15:00  11:15:00  298.0800  298.1084   615088  0.000095
2019-09-05 11:20:00  11:20:00  298.1050  297.8300  1298999 -0.000922
2019-09-05 11:25:00  11:25:00  297.8200  297.8700  1068958  0.000168
2019-09-05 11:30:00  11:30:00  297.8800  298.0500   888313  0.000571
2019-09-05 11:35:00  11:35:00  298.0500  298.1500  1162259  0.000336
2019-09-05 11:40:00  11:40:00  298.1500  298.1700  1522159  0.000067
2019-09-05 11:45:00  11:45:00  298.1700  298.1200  1183108 -0.000168
2019-09-05 11:50:00  11:50:00  298.1100  298.0250   527803 -0.000285
2019-09-05 11:55:00  11:55:00  298.0400  297.9900   947467 -0.000168
2019-09-05 12:00:00  12:00:00  297.9800  297.9700   612299 -0.000034
...                       ...       ...       ...      ...       ...
2019-09-05 13:35:00  13:35:00  297.8600  297.7130   353159 -0.000494
2019-09-05 13:40:00  13:40:00  297.7100  297.7400   462082  0.000101
2019-09-05 13:45:00  13:45:00  297.7500  297.6700   263870 -0.000269
2019-09-05 13:50:00  13:50:00  297.6700  297.6700   365289  0.000000
2019-09-05 13:55:00  13:55:00  297.6800  297.7600   298294  0.000269
2019-09-05 14:00:00  14:00:00  297.7521  297.7100   128511 -0.000141
2019-09-05 14:05:00  14:05:00  297.7050  297.7150   337357  0.000034
2019-09-05 14:10:00  14:10:00  297.7050  297.7400   317955  0.000118
2019-09-05 14:15:00  14:15:00  297.7301  297.8695   778255  0.000468
2019-09-05 14:20:00  14:20:00  297.8700  297.8600   346034 -0.000034
2019-09-05 14:25:00  14:25:00  297.8500  297.5900  1169343 -0.000873
2019-09-05 14:30:00  14:30:00  297.5900  297.7050   220739  0.000386
2019-09-05 14:35:00  14:35:00  297.7100  297.6750   263388 -0.000118
2019-09-05 14:40:00  14:40:00  297.6700  297.7300   436226  0.000202
2019-09-05 14:45:00  14:45:00  297.7300  297.8200   333285  0.000302
2019-09-05 14:50:00  14:50:00  297.8101  297.9000   436948  0.000302
2019-09-05 14:55:00  14:55:00  297.9000  297.8500   727225 -0.000168
2019-09-05 15:00:00  15:00:00  297.8400  297.9600   267017  0.000403
2019-09-05 15:05:00  15:05:00  297.9600  298.0350   971311  0.000252
2019-09-05 15:10:00  15:10:00  298.0400  297.9900   401669 -0.000168
2019-09-05 15:15:00  15:15:00  297.9816  298.1050   438493  0.000414
2019-09-05 15:20:00  15:20:00  298.1050  298.1700   401292  0.000218
2019-09-05 15:25:00  15:25:00  298.1750  298.1300   707221 -0.000151
2019-09-05 15:30:00  15:30:00  298.1300  298.2250   748505  0.000319
2019-09-05 15:35:00  15:35:00  298.2200  298.2700  1277940  0.000168
2019-09-05 15:40:00  15:40:00  298.2750  298.0850   984129 -0.000637
2019-09-05 15:45:00  15:45:00  298.1150  298.0600  1081093 -0.000184
2019-09-05 15:50:00  15:50:00  298.0600  297.8200  1265442 -0.000805
2019-09-05 15:55:00  15:55:00  297.8200  297.9650  2434390  0.000487
2019-09-05 16:00:00  16:00:00  297.9700  297.8400  3822621 -0.000436

[78 rows x 5 columns],                          time      open     close   volume   Returns
date
2019-09-06 09:35:00  09:35:00  298.1700  297.8500        0 -0.001073
2019-09-06 09:40:00  09:40:00  297.8400  297.6500  1233430 -0.000638
2019-09-06 09:45:00  09:45:00  297.6400  297.5100   886851 -0.000437
2019-09-06 09:50:00  09:50:00  297.5000  298.1700  1445195  0.002252
2019-09-06 09:55:00  09:55:00  298.1600  298.1080   812997 -0.000174
2019-09-06 10:00:00  10:00:00  298.1200  297.9600  1053214 -0.000537
2019-09-06 10:05:00  10:05:00  297.9500  297.9600   609805  0.000034
2019-09-06 10:10:00  10:10:00  297.9800  297.8600   876193 -0.000403
2019-09-06 10:15:00  10:15:00  297.8900  298.1000   348792  0.000705
2019-09-06 10:20:00  10:20:00  298.1000  298.0100   622798 -0.000302
2019-09-06 10:25:00  10:25:00  298.0050  298.3000   399462  0.000990
2019-09-06 10:30:00  10:30:00  298.3100  298.4100   531384  0.000335
2019-09-06 10:35:00  10:35:00  298.4200  298.3600   500732 -0.000201
2019-09-06 10:40:00  10:40:00  298.3600  298.4000   429622  0.000134
2019-09-06 10:45:00  10:45:00  298.4100  298.5100   377999  0.000335
2019-09-06 10:50:00  10:50:00  298.5100  298.5601   364996  0.000168
2019-09-06 10:55:00  10:55:00  298.5700  298.5100   372901 -0.000201
2019-09-06 11:00:00  11:00:00  298.5100  298.4200   297219 -0.000301
2019-09-06 11:05:00  11:05:00  298.4300  298.3900   303869 -0.000134
2019-09-06 11:10:00  11:10:00  298.3844  298.4300   351227  0.000153
2019-09-06 11:15:00  11:15:00  298.4400  298.4200   317084 -0.000067
2019-09-06 11:20:00  11:20:00  298.4200  298.3700   291757 -0.000168
2019-09-06 11:25:00  11:25:00  298.3700  298.3950   152642  0.000084
2019-09-06 11:30:00  11:30:00  298.4600  298.3900   255968 -0.000235
2019-09-06 11:35:00  11:35:00  298.3900  298.3000   409084 -0.000302
2019-09-06 11:40:00  11:40:00  298.3000  298.3400   407073  0.000134
2019-09-06 11:45:00  11:45:00  298.3300  298.3800   252109  0.000168
2019-09-06 11:50:00  11:50:00  298.3900  298.3350   240953 -0.000184
2019-09-06 11:55:00  11:55:00  298.3300  298.2200   162621 -0.000369
2019-09-06 12:00:00  12:00:00  298.2400  298.2200   543900 -0.000067
...                       ...       ...       ...      ...       ...
2019-09-06 13:35:00  13:35:00  298.6200  298.6200   685299  0.000000
2019-09-06 13:40:00  13:40:00  298.6182  298.6395   303644  0.000071
2019-09-06 13:45:00  13:45:00  298.6300  298.5900   175410 -0.000134
2019-09-06 13:50:00  13:50:00  298.5900  298.6000   259560  0.000033
2019-09-06 13:55:00  13:55:00  298.6000  298.6050   150390  0.000017
2019-09-06 14:00:00  14:00:00  298.6100  298.6300   171645  0.000067
2019-09-06 14:05:00  14:05:00  298.6300  298.5020   274305 -0.000429
2019-09-06 14:10:00  14:10:00  298.5100  298.5250   388852  0.000050
2019-09-06 14:15:00  14:15:00  298.5265  298.5500   801233  0.000079
2019-09-06 14:20:00  14:20:00  298.5500  298.5300   219122 -0.000067
2019-09-06 14:25:00  14:25:00  298.5400  298.4900   242251 -0.000167
2019-09-06 14:30:00  14:30:00  298.5000  298.5250   248193  0.000084
2019-09-06 14:35:00  14:35:00  298.5316  298.5500   307506  0.000062
2019-09-06 14:40:00  14:40:00  298.5500  298.5100   199701 -0.000134
2019-09-06 14:45:00  14:45:00  298.5100  298.4300   357363 -0.000268
2019-09-06 14:50:00  14:50:00  298.4300  298.4700   328933  0.000134
2019-09-06 14:55:00  14:55:00  298.4600  298.3800   381945 -0.000268
2019-09-06 15:00:00  15:00:00  298.3800  298.4100   346348  0.000101
2019-09-06 15:05:00  15:05:00  298.4100  298.3500   482997 -0.000201
2019-09-06 15:10:00  15:10:00  298.3500  298.3461   886008 -0.000013
2019-09-06 15:15:00  15:15:00  298.3400  298.4100   348513  0.000235
2019-09-06 15:20:00  15:20:00  298.4150  298.3700   380836 -0.000151
2019-09-06 15:25:00  15:25:00  298.3650  298.4900   444927  0.000419
2019-09-06 15:30:00  15:30:00  298.4900  298.5900   673059  0.000335
2019-09-06 15:35:00  15:35:00  298.5900  298.6000   671604  0.000033
2019-09-06 15:40:00  15:40:00  298.6000  298.4400   627779 -0.000536
2019-09-06 15:45:00  15:45:00  298.4350  298.2701  1519867 -0.000553
2019-09-06 15:50:00  15:50:00  298.2750  298.2151  1177690 -0.000201
2019-09-06 15:55:00  15:55:00  298.2100  298.0400  1994129 -0.000570
2019-09-06 16:00:00  16:00:00  298.0300  298.0800  2795747  0.000168

[78 rows x 5 columns],                          time      open     close   volume   Returns
date
2019-09-09 09:35:00  09:35:00  299.1400  298.7100        0 -0.001437
2019-09-09 09:40:00  09:40:00  298.7100  298.6200   854201 -0.000301
2019-09-09 09:45:00  09:45:00  298.6300  298.6900  1332826  0.000201
2019-09-09 09:50:00  09:50:00  298.6900  298.6000   556978 -0.000301
2019-09-09 09:55:00  09:55:00  298.5900  298.5180   737226 -0.000241
2019-09-09 10:00:00  10:00:00  298.5200  298.3200   703260 -0.000670
2019-09-09 10:05:00  10:05:00  298.3200  298.4800   774932  0.000536
2019-09-09 10:10:00  10:10:00  298.4800  298.6000   443350  0.000402
2019-09-09 10:15:00  10:15:00  298.5971  298.6100   574047  0.000043
2019-09-09 10:20:00  10:20:00  298.6100  298.6800   323432  0.000234
2019-09-09 10:25:00  10:25:00  298.6773  298.7200  1145704  0.000143
2019-09-09 10:30:00  10:30:00  298.7100  298.6800   280792 -0.000100
2019-09-09 10:35:00  10:35:00  298.6860  298.7300   477859  0.000147
2019-09-09 10:40:00  10:40:00  298.7300  298.6700   323235 -0.000201
2019-09-09 10:45:00  10:45:00  298.6600  298.7100   279647  0.000167
2019-09-09 10:50:00  10:50:00  298.7200  298.6900   333126 -0.000100
2019-09-09 10:55:00  10:55:00  298.6900  298.7900   492577  0.000335
2019-09-09 11:00:00  11:00:00  298.7800  298.8400   471439  0.000201
2019-09-09 11:05:00  11:05:00  298.8500  298.8100   404189 -0.000134
2019-09-09 11:10:00  11:10:00  298.8100  298.7300   706226 -0.000268
2019-09-09 11:15:00  11:15:00  298.7300  298.7600   804896  0.000100
2019-09-09 11:20:00  11:20:00  298.7600  298.6900   373084 -0.000234
2019-09-09 11:25:00  11:25:00  298.7000  298.6500   327564 -0.000167
2019-09-09 11:30:00  11:30:00  298.6500  298.6900   244595  0.000134
2019-09-09 11:35:00  11:35:00  298.6800  298.6900   765634  0.000033
2019-09-09 11:40:00  11:40:00  298.6900  298.5700   197838 -0.000402
2019-09-09 11:45:00  11:45:00  298.5600  298.5000   318355 -0.000201
2019-09-09 11:50:00  11:50:00  298.4950  298.4850   705675 -0.000034
2019-09-09 11:55:00  11:55:00  298.4800  298.4800   679549  0.000000
2019-09-09 12:00:00  12:00:00  298.4900  298.5200   228615  0.000101
...                       ...       ...       ...      ...       ...
2019-09-09 13:35:00  13:35:00  297.5950  297.5400   815521 -0.000185
2019-09-09 13:40:00  13:40:00  297.5400  297.5900   370402  0.000168
2019-09-09 13:45:00  13:45:00  297.5900  297.5403   508183 -0.000167
2019-09-09 13:50:00  13:50:00  297.5400  297.7700   334024  0.000773

In [27]:
sept3=list_of_df[0]
sept4=list_of_df[1]
sept5=list_of_df[2]
sept6=list_of_df[3]
sept9=list_of_df[4]
sept10=list_of_df[5]
sept11=list_of_df[6]
sept12=list_of_df[7]
sept13=list_of_df[8]
sept16=list_of_df[9]
sept17=list_of_df[10]
sept18=list_of_df[11]

## We have lists of each day containing open & close, we now need to run mean's and std's on each day in the 12 Day period loc'd by hour

### Each day contains this many data points =78 5 min intervals

In [28]:
# grouped_df = returns_df.groupby(returns_df.index.day).count()
# grouped_df

## Daily loc

In [29]:
def sorter(dataframe):
    
    a = dataframe.iloc[:6:]
    b = dataframe.iloc[6:18:]
    c = dataframe.iloc[18:30:]
    d = dataframe.iloc[30:42:]
    e = dataframe.iloc[42:54:]
    f = dataframe.iloc[54:66:]
    g = dataframe.iloc[66:78:]
    
    returns = [a,b,c,d,e,f,g]
    
    raw_list = []
    for x in returns:

        mean_blah = x.mean()
        raw_list.append(mean_blah)
        
    std_list = []
    for x in returns:
    
        std_var = x.std()
        std_list.append(std_var)
    
    print(raw_list)
    print(std_list)

In [30]:
new_list = []

new_nums = sorter(sept4['Returns'])

[-0.0001279349683217844, -2.33774287433168e-05, 0.00015269745818534, 1.93022684518198e-05, -0.00010091165177883666, 9.133583924321649e-05, 0.00012348496955726465]
[0.00022831872897462915, 0.0005774043715841789, 0.0003857131714061791, 0.00033735258778212345, 0.00027030438038316146, 0.00027293725342615203, 0.0003454594951006552]

In [31]:
a = returns_df.iloc[:6:]
b = returns_df.iloc[6:18:]
c = returns_df.iloc[18:30:]
d = returns_df.iloc[30:42:]
e = returns_df.iloc[42:54:]
f = returns_df.iloc[54:66:]
g = returns_df.iloc[66:78:]


list_of_ranges = [a,b,c,d,e,f,g]

In [32]:
list_of_ranges

[                         time   Returns   volume
 date
 2019-09-03 09:35:00  09:35:00  0.000137  4822146
 2019-09-03 09:40:00  09:40:00  0.001170  1320719
 2019-09-03 09:45:00  09:45:00  0.000481   738767
 2019-09-03 09:50:00  09:50:00 -0.000739   791261
 2019-09-03 09:55:00  09:55:00  0.002028   996429
 2019-09-03 10:00:00  10:00:00 -0.000446   469532,
                          time   Returns   volume
 date
 2019-09-03 10:05:00  10:05:00 -0.004877  5496366
 2019-09-03 10:10:00  10:10:00 -0.000259  1865194
 2019-09-03 10:15:00  10:15:00 -0.000725  1364689
 2019-09-03 10:20:00  10:20:00  0.001278  1196459
 2019-09-03 10:25:00  10:25:00  0.000000  1079803
 2019-09-03 10:30:00  10:30:00  0.001484   843739
 2019-09-03 10:35:00  10:35:00 -0.000896   858742
 2019-09-03 10:40:00  10:40:00  0.000362   690629
 2019-09-03 10:45:00  10:45:00  0.001241  1342137
 2019-09-03 10:50:00  10:50:00  0.000207   729874
 2019-09-03 10:55:00  10:55:00  0.000757   629405
 2019-09-03 11:00:00  11:00:00  0.000413   815404,
                          time   Returns   volume
 date
 2019-09-03 11:05:00  11:05:00 -0.001135   755109
 2019-09-03 11:10:00  11:10:00  0.000000   671076
 2019-09-03 11:15:00  11:15:00 -0.002099   829850
 2019-09-03 11:20:00  11:20:00  0.001052   598221
 2019-09-03 11:25:00  11:25:00  0.000724   533074
 2019-09-03 11:30:00  11:30:00  0.000276  1462735
 2019-09-03 11:35:00  11:35:00  0.000310   622800
 2019-09-03 11:40:00  11:40:00  0.000516   640993
 2019-09-03 11:45:00  11:45:00 -0.000069   260992
 2019-09-03 11:50:00  11:50:00  0.001342   611509
 2019-09-03 11:55:00  11:55:00 -0.000402   295219
 2019-09-03 12:00:00  12:00:00 -0.000825   256612,
                          time   Returns   volume
 date
 2019-09-03 12:05:00  12:05:00  0.000327   319544
 2019-09-03 12:10:00  12:10:00 -0.001135   311238
 2019-09-03 12:15:00  12:15:00  0.000568   211822
 2019-09-03 12:20:00  12:20:00  0.000344   325882
 2019-09-03 12:25:00  12:25:00 -0.000585   345996
 2019-09-03 12:30:00  12:30:00 -0.000069   229812
 2019-09-03 12:35:00  12:35:00 -0.000585  1288912
 2019-09-03 12:40:00  12:40:00  0.000758   203589
 2019-09-03 12:45:00  12:45:00 -0.000155   132064
 2019-09-03 12:50:00  12:50:00  0.000895   318060
 2019-09-03 12:55:00  12:55:00 -0.001548   260714
 2019-09-03 13:00:00  13:00:00  0.000138   230757,
                          time   Returns  volume
 date
 2019-09-03 13:05:00  13:05:00 -0.000138  406809
 2019-09-03 13:10:00  13:10:00  0.000131  392840
 2019-09-03 13:15:00  13:15:00  0.000287  379080
 2019-09-03 13:20:00  13:20:00 -0.000223  363890
 2019-09-03 13:25:00  13:25:00 -0.000620  340861
 2019-09-03 13:30:00  13:30:00  0.000276  275440
 2019-09-03 13:35:00  13:35:00 -0.000844  565814
 2019-09-03 13:40:00  13:40:00  0.000103  583137
 2019-09-03 13:45:00  13:45:00 -0.000397  432740
 2019-09-03 13:50:00  13:50:00  0.000138  863105
 2019-09-03 13:55:00  13:55:00 -0.000793  467943
 2019-09-03 14:00:00  14:00:00  0.000311  209199,
                          time   Returns  volume
 date
 2019-09-03 14:05:00  14:05:00  0.000690  357103
 2019-09-03 14:10:00  14:10:00 -0.000074  187631
 2019-09-03 14:15:00  14:15:00  0.000224  320083
 2019-09-03 14:20:00  14:20:00 -0.000517  327984
 2019-09-03 14:25:00  14:25:00 -0.000242  321744
 2019-09-03 14:30:00  14:30:00  0.000776  178488
 2019-09-03 14:35:00  14:35:00 -0.000310  425579
 2019-09-03 14:40:00  14:40:00  0.000379  387009
 2019-09-03 14:45:00  14:45:00  0.000190  305891
 2019-09-03 14:50:00  14:50:00  0.000000  388879
 2019-09-03 14:55:00  14:55:00  0.000274  691893
 2019-09-03 15:00:00  15:00:00  0.000034  303748,
                          time   Returns   volume
 date
 2019-09-03 15:05:00  15:05:00 -0.000546   622163
 2019-09-03 15:10:00  15:10:00  0.000552   866722
 2019-09-03 15:15:00  15:15:00 -0.000034   422380
 2019-09-03 15:20:00  15:20:00  0.000741   525500
 2019-09-03 15:25:00  15:25:00  0.000344   519614
 2019-09-03 15:30:00  15:30:00 -0.000155   560434
 2019-09-03 15:35:00  15:35:00  0.000379   648505
 2019-09-03 15:40:00  15:40:00  0.000199   585010
 2019-09-03 15:45:00  15:45:00 -0.000275   653671
 2019-09-03 15:50:00  15:50:00  0.000413   848093
 2019-09-03 15:55:00  15:55:00  0.000894  1756085
 2019-09-03 16:00:00  16:00:00 -0.000619  2411640]

In [36]:
list_of_ranges

[                         time   Returns   volume
 date
 2019-09-03 09:35:00  09:35:00  0.000137  4822146
 2019-09-03 09:40:00  09:40:00  0.001170  1320719
 2019-09-03 09:45:00  09:45:00  0.000481   738767
 2019-09-03 09:50:00  09:50:00 -0.000739   791261
 2019-09-03 09:55:00  09:55:00  0.002028   996429
 2019-09-03 10:00:00  10:00:00 -0.000446   469532,
                          time   Returns   volume
 date
 2019-09-03 10:05:00  10:05:00 -0.004877  5496366
 2019-09-03 10:10:00  10:10:00 -0.000259  1865194
 2019-09-03 10:15:00  10:15:00 -0.000725  1364689
 2019-09-03 10:20:00  10:20:00  0.001278  1196459
 2019-09-03 10:25:00  10:25:00  0.000000  1079803
 2019-09-03 10:30:00  10:30:00  0.001484   843739
 2019-09-03 10:35:00  10:35:00 -0.000896   858742
 2019-09-03 10:40:00  10:40:00  0.000362   690629
 2019-09-03 10:45:00  10:45:00  0.001241  1342137
 2019-09-03 10:50:00  10:50:00  0.000207   729874
 2019-09-03 10:55:00  10:55:00  0.000757   629405
 2019-09-03 11:00:00  11:00:00  0.000413   815404,
                          time   Returns   volume
 date
 2019-09-03 11:05:00  11:05:00 -0.001135   755109
 2019-09-03 11:10:00  11:10:00  0.000000   671076
 2019-09-03 11:15:00  11:15:00 -0.002099   829850
 2019-09-03 11:20:00  11:20:00  0.001052   598221
 2019-09-03 11:25:00  11:25:00  0.000724   533074
 2019-09-03 11:30:00  11:30:00  0.000276  1462735
 2019-09-03 11:35:00  11:35:00  0.000310   622800
 2019-09-03 11:40:00  11:40:00  0.000516   640993
 2019-09-03 11:45:00  11:45:00 -0.000069   260992
 2019-09-03 11:50:00  11:50:00  0.001342   611509
 2019-09-03 11:55:00  11:55:00 -0.000402   295219
 2019-09-03 12:00:00  12:00:00 -0.000825   256612,
                          time   Returns   volume
 date
 2019-09-03 12:05:00  12:05:00  0.000327   319544
 2019-09-03 12:10:00  12:10:00 -0.001135   311238
 2019-09-03 12:15:00  12:15:00  0.000568   211822
 2019-09-03 12:20:00  12:20:00  0.000344   325882
 2019-09-03 12:25:00  12:25:00 -0.000585   345996
 2019-09-03 12:30:00  12:30:00 -0.000069   229812
 2019-09-03 12:35:00  12:35:00 -0.000585  1288912
 2019-09-03 12:40:00  12:40:00  0.000758   203589
 2019-09-03 12:45:00  12:45:00 -0.000155   132064
 2019-09-03 12:50:00  12:50:00  0.000895   318060
 2019-09-03 12:55:00  12:55:00 -0.001548   260714
 2019-09-03 13:00:00  13:00:00  0.000138   230757,
                          time   Returns  volume
 date
 2019-09-03 13:05:00  13:05:00 -0.000138  406809
 2019-09-03 13:10:00  13:10:00  0.000131  392840
 2019-09-03 13:15:00  13:15:00  0.000287  379080
 2019-09-03 13:20:00  13:20:00 -0.000223  363890
 2019-09-03 13:25:00  13:25:00 -0.000620  340861
 2019-09-03 13:30:00  13:30:00  0.000276  275440
 2019-09-03 13:35:00  13:35:00 -0.000844  565814
 2019-09-03 13:40:00  13:40:00  0.000103  583137
 2019-09-03 13:45:00  13:45:00 -0.000397  432740
 2019-09-03 13:50:00  13:50:00  0.000138  863105
 2019-09-03 13:55:00  13:55:00 -0.000793  467943
 2019-09-03 14:00:00  14:00:00  0.000311  209199,
                          time   Returns  volume
 date
 2019-09-03 14:05:00  14:05:00  0.000690  357103
 2019-09-03 14:10:00  14:10:00 -0.000074  187631
 2019-09-03 14:15:00  14:15:00  0.000224  320083
 2019-09-03 14:20:00  14:20:00 -0.000517  327984
 2019-09-03 14:25:00  14:25:00 -0.000242  321744
 2019-09-03 14:30:00  14:30:00  0.000776  178488
 2019-09-03 14:35:00  14:35:00 -0.000310  425579
 2019-09-03 14:40:00  14:40:00  0.000379  387009
 2019-09-03 14:45:00  14:45:00  0.000190  305891
 2019-09-03 14:50:00  14:50:00  0.000000  388879
 2019-09-03 14:55:00  14:55:00  0.000274  691893
 2019-09-03 15:00:00  15:00:00  0.000034  303748,
                          time   Returns   volume
 date
 2019-09-03 15:05:00  15:05:00 -0.000546   622163
 2019-09-03 15:10:00  15:10:00  0.000552   866722
 2019-09-03 15:15:00  15:15:00 -0.000034   422380
 2019-09-03 15:20:00  15:20:00  0.000741   525500
 2019-09-03 15:25:00  15:25:00  0.000344   519614
 2019-09-03 15:30:00  15:30:00 -0.000155   560434
 2019-09-03 15:35:00  15:35:00  0.000379   648505
 2019-09-03 15:40:00  15:40:00  0.000199   585010
 2019-09-03 15:45:00  15:45:00 -0.000275   653671
 2019-09-03 15:50:00  15:50:00  0.000413   848093
 2019-09-03 15:55:00  15:55:00  0.000894  1756085
 2019-09-03 16:00:00  16:00:00 -0.000619  2411640]

In [ ]:
#Statistical Analysis
## Chi Square test to identify different individual hourly mean and st.dev compared to benchmark of all hours mean and st. dev