In [60]:
import pandas as pd
from pathlib import Path

In [61]:
spy_path = Path('spy_data_frame.csv')
spy_df = pd.read_csv(spy_path)
spy_df.head(25)

                   date      high       low      open     close    volume
0   2019-09-18 15:30:00  301.2200  300.0050  300.0050  301.0900  10191171
1   2019-09-18 14:30:00  300.3575  298.5257  298.5720  300.0220  24600903
2   2019-09-18 13:30:00  300.5200  298.5700  299.6800  298.7800  15185359
3   2019-09-18 12:30:00  300.2450  299.6600  300.1550  299.6900   3569031
4   2019-09-18 11:30:00  300.2400  300.0200  300.1400  300.1500   3181030
5   2019-09-18 10:30:00  300.5700  300.1000  300.5000  300.1400   4130207
6   2019-09-18 09:30:00  300.8166  300.1260  300.4959  300.5159   7099381
7   2019-09-17 15:30:00  301.0200  300.4100  300.4350  300.9400   6118041
8   2019-09-17 14:30:00  300.4500  300.1600  300.1950  300.4400   4474781
9   2019-09-17 13:30:00  300.6000  300.0800  300.0900  300.2000   4989877
10  2019-09-17 12:30:00  300.2500  299.9300  300.1300  300.1000   3135163
11  2019-09-17 11:30:00  300.4700  299.9800  300.2700  300.1200   3212445
12  2019-09-17 10:30:00  300.5700  299.9700  300.1650  300.2700   5084341
13  2019-09-17 09:30:00  300.3900  299.7500  299.9400  300.1700  11200221
14  2019-09-16 15:30:00  300.3100  299.9700  300.0800  300.1600   6585705
15  2019-09-16 14:30:00  300.4300  300.0200  300.2800  300.0789   7062908
16  2019-09-16 13:30:00  300.3800  299.9600  300.0800  300.2800   5706634
17  2019-09-16 12:30:00  300.1600  299.5800  299.8200  300.0900   8362554
18  2019-09-16 11:30:00  300.6815  299.7306  300.3612  299.8212   5992253
19  2019-09-16 10:30:00  300.7915  300.0259  300.1059  300.3659   5532843
20  2019-09-16 09:30:00  300.6500  299.7000  299.8400  300.0900   9802671
21  2019-09-13 15:30:00  301.3700  300.9300  300.9500  301.0500   8657614
22  2019-09-13 14:30:00  301.6224  300.9617  301.2312  300.9975   4317663
23  2019-09-13 13:30:00  301.4800  301.0200  301.4700  301.2100   7714476
24  2019-09-13 12:30:00  301.6100  301.3000  301.3900  301.4700   4033858

In [62]:
spy_df['Time'] = pd.to_datetime(spy_df['date']).dt.time
spy_df['Date'] = pd.to_datetime(spy_df['date']).dt.date

time_index_df = spy_df.set_index('Time').drop(columns='date')
time_index_df

              high       low      open     close    volume        Date
Time
15:30:00  301.2200  300.0050  300.0050  301.0900  10191171  2019-09-18
14:30:00  300.3575  298.5257  298.5720  300.0220  24600903  2019-09-18
13:30:00  300.5200  298.5700  299.6800  298.7800  15185359  2019-09-18
12:30:00  300.2450  299.6600  300.1550  299.6900   3569031  2019-09-18
11:30:00  300.2400  300.0200  300.1400  300.1500   3181030  2019-09-18
10:30:00  300.5700  300.1000  300.5000  300.1400   4130207  2019-09-18
09:30:00  300.8166  300.1260  300.4959  300.5159   7099381  2019-09-18
15:30:00  301.0200  300.4100  300.4350  300.9400   6118041  2019-09-17
14:30:00  300.4500  300.1600  300.1950  300.4400   4474781  2019-09-17
13:30:00  300.6000  300.0800  300.0900  300.2000   4989877  2019-09-17
12:30:00  300.2500  299.9300  300.1300  300.1000   3135163  2019-09-17
11:30:00  300.4700  299.9800  300.2700  300.1200   3212445  2019-09-17
10:30:00  300.5700  299.9700  300.1650  300.2700   5084341  2019-09-17
09:30:00  300.3900  299.7500  299.9400  300.1700  11200221  2019-09-17
15:30:00  300.3100  299.9700  300.0800  300.1600   6585705  2019-09-16
14:30:00  300.4300  300.0200  300.2800  300.0789   7062908  2019-09-16
13:30:00  300.3800  299.9600  300.0800  300.2800   5706634  2019-09-16
12:30:00  300.1600  299.5800  299.8200  300.0900   8362554  2019-09-16
11:30:00  300.6815  299.7306  300.3612  299.8212   5992253  2019-09-16
10:30:00  300.7915  300.0259  300.1059  300.3659   5532843  2019-09-16
09:30:00  300.6500  299.7000  299.8400  300.0900   9802671  2019-09-16
15:30:00  301.3700  300.9300  300.9500  301.0500   8657614  2019-09-13
14:30:00  301.6224  300.9617  301.2312  300.9975   4317663  2019-09-13
13:30:00  301.4800  301.0200  301.4700  301.2100   7714476  2019-09-13
12:30:00  301.6100  301.3000  301.3900  301.4700   4033858  2019-09-13
11:30:00  301.8600  301.2975  301.7600  301.3900   9944862  2019-09-13
10:30:00  302.1700  301.5600  301.7700  301.7100   8478693  2019-09-13
09:30:00  302.3005  301.5498  301.7476  301.7926  10320054  2019-09-13
15:30:00  302.0900  301.2700  301.9600  301.2700   8644319  2019-09-12
14:30:00  302.3600  301.8800  302.0300  301.9000   6039054  2019-09-12
...            ...       ...       ...       ...       ...         ...
10:30:00  296.0800  295.2900  295.7200  295.3100   7820132  2019-07-01
09:30:00  296.9200  295.6800  296.6800  295.7200  18364933  2019-07-01
15:30:00  293.4600  292.2300  292.3000  293.4400   9098557  2019-06-28
14:30:00  292.6900  292.2700  292.5800  292.3000   6390104  2019-06-28
13:30:00  292.8700  292.4600  292.7552  292.5800   3724298  2019-06-28
12:30:00  293.1400  292.6800  293.0600  292.7550   4263889  2019-06-28
11:30:00  293.1900  292.3548  292.3850  293.0600   4861667  2019-06-28
10:30:00  292.5400  292.0400  292.1350  292.3900   4179558  2019-06-28
09:30:00  292.8300  292.0100  292.5800  292.1351   8376918  2019-06-28
15:30:00  291.9000  291.4700  291.6600  291.7500   5667195  2019-06-27
14:30:00  292.0500  291.5600  291.9450  291.6625   3144684  2019-06-27
13:30:00  292.0600  291.7800  291.9200  291.9450   3720048  2019-06-27
12:30:00  291.9300  291.6300  291.6300  291.9200   2663622  2019-06-27
11:30:00  291.8250  290.9800  291.1100  291.6200   3757354  2019-06-27
10:30:00  291.8300  290.8900  291.6300  291.1100   6468791  2019-06-27
09:30:00  291.9600  291.2200  291.3100  291.6200   7734921  2019-06-27
15:30:00  291.0600  290.4000  290.6800  290.4600   9311002  2019-06-26
14:30:00  291.2703  290.6147  291.0005  290.6805   7917761  2019-06-26
13:30:00  291.4228  290.9724  291.0209  290.9959   4423273  2019-06-26
12:30:00  291.6800  291.0100  291.3800  291.0150   2939934  2019-06-26
11:30:00  291.5800  291.1100  291.4900  291.3800   3782751  2019-06-26
10:30:00  291.8000  291.2050  291.2900  291.4800   4108800  2019-06-26
09:30:00  292.3100  291.0400  291.7500  291.2900  10808244  2019-06-26
15:30:00  291.4000  290.6400  291.3000  290.7900  16812883  2019-06-25
14:30:00  291.8282  290.9924  291.4709  291.3209  10988759  2019-06-25
13:30:00  292.4600  291.4300  292.0800  291.4700   7191593  2019-06-25
12:30:00  292.8735  291.5723  292.5477  292.0877   9687678  2019-06-25
11:30:00  292.7600  292.3800  292.6100  292.5300   4527747  2019-06-25
10:30:00  293.2017  292.5067  292.7893  292.6193   8439064  2019-06-25
09:30:00  294.0126  292.6513  293.7123  292.7922   9782850  2019-06-25

[417 rows x 6 columns]

In [63]:
time_index_df.iloc[2::7]

              high       low      open     close    volume        Date
Time
13:30:00  300.5200  298.5700  299.6800  298.7800  15185359  2019-09-18
13:30:00  300.6000  300.0800  300.0900  300.2000   4989877  2019-09-17
13:30:00  300.3800  299.9600  300.0800  300.2800   5706634  2019-09-16
13:30:00  301.4800  301.0200  301.4700  301.2100   7714476  2019-09-13
13:30:00  302.3700  301.8900  302.0700  302.0300   6918459  2019-09-12
13:30:00  299.8700  299.4200  299.7250  299.4908   5876439  2019-09-11
13:30:00  297.5500  296.7300  297.1700  296.7600   3187262  2019-09-10
13:30:00  297.9100  297.3900  297.5950  297.5000   4546050  2019-09-09
13:30:00  298.7600  298.4300  298.6200  298.5250   3919531  2019-09-06
13:30:00  297.9200  297.5300  297.8600  297.7050   5040888  2019-09-05
13:30:00  293.8211  293.2806  293.5458  293.4058   3291589  2019-09-04
13:30:00  290.5212  289.8706  290.2076  290.0076   4756925  2019-09-03
13:30:00  293.0500  292.4400  292.5100  292.6800   4966007  2019-08-30
13:30:00  293.1600  292.5000  292.6450  292.8700   4824831  2019-08-29
13:30:00  288.7400  288.2700  288.4000  288.5500   4089746  2019-08-28
13:30:00  287.6900  286.6400  286.8600  287.0135   6671422  2019-08-27
13:30:00  287.3650  286.4600  287.3650  286.5800   3720589  2019-08-26
13:30:00  286.9000  285.8100  285.9409  286.2200   8019987  2019-08-23
13:30:00  292.8400  292.3110  292.6100  292.3400   3996221  2019-08-22
13:30:00  292.9400  291.9800  292.5600  292.5900   6303768  2019-08-21
13:30:00  291.8861  290.6348  291.5693  290.7692   7319100  2019-08-20
13:30:00  292.8600  292.4100  292.8500  292.5950   4067824  2019-08-19
13:30:00  289.0500  288.5500  289.0300  288.6300   4912889  2019-08-16
13:30:00  284.7866  282.6546  284.3106  284.0756  14667456  2019-08-15
13:30:00  285.9900  284.8700  285.3600  284.9300   9846410  2019-08-14
13:30:00  293.1000  292.3800  292.5700  293.0600   4199709  2019-08-13
13:30:00  289.1500  287.9300  289.0700  287.9900   7710200  2019-08-12
13:30:00  292.5000  291.7700  291.9500  292.1500   8414806  2019-08-09
13:30:00  292.9200  292.1350  292.2500  292.4100   5563959  2019-08-08
13:30:00  287.6000  285.9900  286.0200  287.1100  13061048  2019-08-07
13:30:00  287.5950  285.9900  286.1200  287.5300  10496226  2019-08-06
13:30:00  285.5100  283.3300  284.8800  283.3525  14032008  2019-08-05
13:30:00  292.9571  291.4857  291.5343  292.2293   8492733  2019-08-02
13:30:00  299.2664  294.8422  298.2420  295.3318  41522855  2019-08-01
13:30:00  301.3000  300.0900  300.9400  300.2400  12682762  2019-07-31
13:30:00  301.1600  300.4100  300.4200  301.0350   4700435  2019-07-30
13:30:00  301.7000  301.3300  301.5900  301.5900   2460698  2019-07-29
13:30:00  301.8200  301.6200  301.7300  301.7699   1945853  2019-07-26
13:30:00  300.3000  299.6100  299.6600  300.0800   4806800  2019-07-25
13:30:00  300.7200  300.2250  300.3700  300.6800   4144437  2019-07-24
13:30:00  299.8550  298.8600  298.8600  299.5750   8977972  2019-07-23
13:30:00  298.1200  297.8200  297.8400  297.9000   2170252  2019-07-22
13:30:00  299.2400  298.1802  299.0300  298.2100   5895199  2019-07-19
13:30:00  298.6150  297.4400  297.6200  298.5025   7139929  2019-07-18
13:30:00  299.1300  298.4500  298.8700  298.6600   3103617  2019-07-17
13:30:00  300.2100  299.4700  300.1567  299.6400   3811200  2019-07-16
13:30:00  300.7800  300.3200  300.3600  300.6400   2653760  2019-07-15
13:30:00  300.2200  299.9100  300.0750  300.1450   2939790  2019-07-12
13:30:00  298.8300  298.2000  298.7199  298.3850   7942428  2019-07-11
13:30:00  299.2500  298.4100  298.7900  298.4150   8659568  2019-07-10
13:30:00  296.9800  296.6900  296.7500  296.8700   2880025  2019-07-09
13:30:00  297.0957  296.4952  296.6307  296.5075   3892674  2019-07-08
13:30:00  298.1900  297.9000  297.9700  298.0650   2911719  2019-07-05
10:30:00  298.0500  297.6000  297.6600  297.8300   6558997  2019-07-03
10:30:00  296.1500  295.5500  295.9100  295.6001   8182349  2019-07-02
10:30:00  296.0800  295.2900  295.7200  295.3100   7820132  2019-07-01
10:30:00  292.5400  292.0400  292.1350  292.3900   4179558  2019-06-28
10:30:00  291.8300  290.8900  291.6300  291.1100   6468791  2019-06-27
10:30:00  291.8000  291.2050  291.2900  291.4800   4108800  2019-06-26
10:30:00  293.2017  292.5067  292.7893  292.6193   8439064  2019-06-25

In [66]:
spy_df['Time'] = pd.to_datetime(spy_df['date']).dt.time
spy_df['Date'] = pd.to_datetime(spy_df['date']).dt.date

dropped_time_df = spy_df.drop(columns = 'date')
dropped_time_df =

         high       low      open     close    volume      Time        Date
0    301.2200  300.0050  300.0050  301.0900  10191171  15:30:00  2019-09-18
1    300.3575  298.5257  298.5720  300.0220  24600903  14:30:00  2019-09-18
2    300.5200  298.5700  299.6800  298.7800  15185359  13:30:00  2019-09-18
3    300.2450  299.6600  300.1550  299.6900   3569031  12:30:00  2019-09-18
4    300.2400  300.0200  300.1400  300.1500   3181030  11:30:00  2019-09-18
5    300.5700  300.1000  300.5000  300.1400   4130207  10:30:00  2019-09-18
6    300.8166  300.1260  300.4959  300.5159   7099381  09:30:00  2019-09-18
7    301.0200  300.4100  300.4350  300.9400   6118041  15:30:00  2019-09-17
8    300.4500  300.1600  300.1950  300.4400   4474781  14:30:00  2019-09-17
9    300.6000  300.0800  300.0900  300.2000   4989877  13:30:00  2019-09-17
10   300.2500  299.9300  300.1300  300.1000   3135163  12:30:00  2019-09-17
11   300.4700  299.9800  300.2700  300.1200   3212445  11:30:00  2019-09-17
12   300.5700  299.9700  300.1650  300.2700   5084341  10:30:00  2019-09-17
13   300.3900  299.7500  299.9400  300.1700  11200221  09:30:00  2019-09-17
14   300.3100  299.9700  300.0800  300.1600   6585705  15:30:00  2019-09-16
15   300.4300  300.0200  300.2800  300.0789   7062908  14:30:00  2019-09-16
16   300.3800  299.9600  300.0800  300.2800   5706634  13:30:00  2019-09-16
17   300.1600  299.5800  299.8200  300.0900   8362554  12:30:00  2019-09-16
18   300.6815  299.7306  300.3612  299.8212   5992253  11:30:00  2019-09-16
19   300.7915  300.0259  300.1059  300.3659   5532843  10:30:00  2019-09-16
20   300.6500  299.7000  299.8400  300.0900   9802671  09:30:00  2019-09-16
21   301.3700  300.9300  300.9500  301.0500   8657614  15:30:00  2019-09-13
22   301.6224  300.9617  301.2312  300.9975   4317663  14:30:00  2019-09-13
23   301.4800  301.0200  301.4700  301.2100   7714476  13:30:00  2019-09-13
24   301.6100  301.3000  301.3900  301.4700   4033858  12:30:00  2019-09-13
25   301.8600  301.2975  301.7600  301.3900   9944862  11:30:00  2019-09-13
26   302.1700  301.5600  301.7700  301.7100   8478693  10:30:00  2019-09-13
27   302.3005  301.5498  301.7476  301.7926  10320054  09:30:00  2019-09-13
28   302.0900  301.2700  301.9600  301.2700   8644319  15:30:00  2019-09-12
29   302.3600  301.8800  302.0300  301.9000   6039054  14:30:00  2019-09-12
..        ...       ...       ...       ...       ...       ...         ...
387  296.0800  295.2900  295.7200  295.3100   7820132  10:30:00  2019-07-01
388  296.9200  295.6800  296.6800  295.7200  18364933  09:30:00  2019-07-01
389  293.4600  292.2300  292.3000  293.4400   9098557  15:30:00  2019-06-28
390  292.6900  292.2700  292.5800  292.3000   6390104  14:30:00  2019-06-28
391  292.8700  292.4600  292.7552  292.5800   3724298  13:30:00  2019-06-28
392  293.1400  292.6800  293.0600  292.7550   4263889  12:30:00  2019-06-28
393  293.1900  292.3548  292.3850  293.0600   4861667  11:30:00  2019-06-28
394  292.5400  292.0400  292.1350  292.3900   4179558  10:30:00  2019-06-28
395  292.8300  292.0100  292.5800  292.1351   8376918  09:30:00  2019-06-28
396  291.9000  291.4700  291.6600  291.7500   5667195  15:30:00  2019-06-27
397  292.0500  291.5600  291.9450  291.6625   3144684  14:30:00  2019-06-27
398  292.0600  291.7800  291.9200  291.9450   3720048  13:30:00  2019-06-27
399  291.9300  291.6300  291.6300  291.9200   2663622  12:30:00  2019-06-27
400  291.8250  290.9800  291.1100  291.6200   3757354  11:30:00  2019-06-27
401  291.8300  290.8900  291.6300  291.1100   6468791  10:30:00  2019-06-27
402  291.9600  291.2200  291.3100  291.6200   7734921  09:30:00  2019-06-27
403  291.0600  290.4000  290.6800  290.4600   9311002  15:30:00  2019-06-26
404  291.2703  290.6147  291.0005  290.6805   7917761  14:30:00  2019-06-26
405  291.4228  290.9724  291.0209  290.9959   4423273  13:30:00  2019-06-26
406  291.6800  291.0100  291.3800  291.0150   2939934  12:30:00  2019-06-26
407  291.5800  291.1100  291.4900  291.3800   3782751  11:30:00  2019-06-26
408  291.8000  291.2050  291.2900  291.4800   4108800  10:30:00  2019-06-26
409  292.3100  291.0400  291.7500  291.2900  10808244  09:30:00  2019-06-26
410  291.4000  290.6400  291.3000  290.7900  16812883  15:30:00  2019-06-25
411  291.8282  290.9924  291.4709  291.3209  10988759  14:30:00  2019-06-25
412  292.4600  291.4300  292.0800  291.4700   7191593  13:30:00  2019-06-25
413  292.8735  291.5723  292.5477  292.0877   9687678  12:30:00  2019-06-25
414  292.7600  292.3800  292.6100  292.5300   4527747  11:30:00  2019-06-25
415  293.2017  292.5067  292.7893  292.6193   8439064  10:30:00  2019-06-25
416  294.0126  292.6513  293.7123  292.7922   9782850  09:30:00  2019-06-25

[417 rows x 7 columns]